apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: correct-ipc-api
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: correct-ipc-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
